on:
  issue_comment:
    types: [created]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: try job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo 'insight payload: ${{ toJson(github.event) }}'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          prettier_command: ./node_modules/.bin/prettier --write
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          skip_fetch: true
