on:
  issue_comment:
    types: [created]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: try job
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get branch
        id: pullRequestBranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branch::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.pullRequestBranch.outputs.branch }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          prettier_command: ./node_modules/.bin/prettier --write
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          skip_fetch: true
